### ISSUE TITLE
Give BOS Knights T45 power armour

### ISSUE THREAD

**Issue by CaptainSlumbo** [CrashpointF13/CrashpointF13#119]
The paladin already starts with T51 power armour, and bad deathclaw used have the knights spawn with T45 power armour. I don't know why it was removed or who removed it but it doesn't really make sense considering the six hour timelock and the fact that if the admins are successful in doing what they are supposed to be doing then shitters would never get to the role of knight so any arguements for balance immediately fall apart.

**Comment by Mannybrado** [comment]
🤡

**Comment by SwiGs1** [comment]
#117
