### ISSUE TITLE
Autosurgeon is single use

### ISSUE THREAD

**Issue by CaptainSlumbo** [CrashpointF13/CrashpointF13#130]
pretty sure this is a bug/oversight. The auto-surgeon is single use only and damages you, and the auto-doc is single use and damages you as well so there's no difference despite taking different resources to make. 

I suggest the autosurgeon is changed to do no damage and to be reusable, there's really no point to having it do this other than to mildly annoy BoS.

**Comment by ProbablyCarl** [comment]
Intentional.
