### ISSUE TITLE
Travis is wailing

### ISSUE THREAD

**Issue by Tennessee116** [CrashpointF13/CrashpointF13#147]
**Priority:** Low

**Reproduction:** Try to do any checks with Travis.
![image](https://user-images.githubusercontent.com/57928673/106025141-16dae980-608e-11eb-9963-6a66ddfb8083.png)

**Notes:** You could probably get away with changing to actions just because it's better in general.

**Comment by Mannybrado** [comment]
this isnt fixable, actions wouldnt work either

**Comment by ProbablyCarl** [comment]
Travis is a Goy.
