### ISSUE TITLE
Limited Raider Slots - The Issues

### ISSUE THREAD

**Issue by imw-Oculus** [CrashpointF13/CrashpointF13#45]
Per change: #3a0a2bd
While I respect the intent of the change which limits Raider slots, I've seen other Fallout servers do this - and it's typically not to their benefit.
Let's examine the reason given for the change.

"Unrobust players moaned, and since it's now a rather popular opinion, this is being done."

I would point out that Raiders doing their job - enslaving and robbing people - will inevitably cause whining among the players. I would also state that I haven't seen a single complaint in OOC about this, so any whinging/opinions must be taking place entirely on the Discord.

Now, allow me to examine the impact of limited Raider slots.
- Given that Raiders are a high-fatality position, Raiders will be actively disincentivized from making risky moves, which is the essence of being a Raider.
- This eliminates the possibility of Raider gangs of any substantial size from clashing, as the limited number of slots ensure that there is only the possibility of one Raider gang (at most) forming
- Raiders fulfill a major role in making the Wasteland a dangerous place to travel, when all slots are used up - and all Raiders are dead - this risk is entirely eliminated
- In terms of slot /possibilities/, this change dramatically shifts the balance of power in favor of all other factions - who have a huge incentive to kill any Raiders they come across.

I'm sure there will be many more negative impacts to observe, and I think that these generally outweigh the given reasons for making the change in the first place. I would suggest, if the cap not be removed entirely, that it be generously increased to something like 25.

**Comment by ProbablyCarl** [comment]
I appreciate the comments. I'll be bumping raider back to unlimited, as we've a map rotation now.

**Comment by imw-Oculus** [comment]
Absolutely based. You can go ahead and close this issue, then. Thanks Carl.
