### ISSUE TITLE
Police Pistol Fire Delay

### ISSUE THREAD

**Issue by imw-Oculus** [CrashpointF13/CrashpointF13#52]
I'm eschewing the format - since this really is a simple, non-critical matter.
Per file: https://github.com/CrashpointF13/CrashpointF13/blob/master/code/modules/projectiles/guns/ballistic/revolver.dm

The Police Pistol has a Fire Delay of 0. I was told on the Discord that this was likely an oversight, rather than intentional - and I'm inclined to agree. Given the flexibility of the weapon (its ability to utilize two different types of ammo with no drawbacks) - I would recommend a fire_delay of 1 or 2. 

I'd sort this one out myself, but I'm still working on getting my github set up.

**Comment by imw-Oculus** [comment]
Looks like the Pipe Rifle suffers the same issue, though that might be balanced considering the 15 Spread.

**Comment by Afya212** [comment]
Merged
