### ISSUE TITLE
add timelocks for jobs

### ISSUE THREAD

**Issue by CaptainSlumbo** [CrashpointF13/CrashpointF13#58]
adding timelocks would help in preventing lame command staff and lowrp stuff, i've seen a lot of support for this idea so i'm officially requesting it.

Add timelocks to NCR/LEGION
NCR
+ add a sergeant time lock of 1-2 hours, so people have to play one full game before they can be in charge of others
+ add a timelock to NCR's lieutenant role so that you have to play a few rounds as an NCO before you can play as a CO. anywhere from 2-6 hours seems reasonable to me.
I don't think the captain/ambassador or any of the lower ranks need to be changed.

LEGION
+ add legion vexillarius timelock of 1-2 hours so people have to play one full game as legion before they can be in charge of others
+ add a timelock to decanus

I think these changes will be very useful in making the server more interesting in the longterm.
restricting access to positions that affect rounds pretty heavily to people who have at least played the faction once before is the basic goal of this request.

**Comment by imw-Oculus** [comment]
Mostly agreed. If you're giving other people orders, you should have at least some level of experience with the role.
