### ISSUE TITLE
NCR Chat Color

### ISSUE THREAD

**Issue by imw-Oculus** [CrashpointF13/CrashpointF13#91]
Right now, the light orange against the white background of the text box is more difficult to read than it needs to be. I'd recommend a nice, bright yellow.
Very low priority.

**Comment by CaptainSlumbo** [comment]
i think it would be better to just add nightmode, i believe chat is changing to goonchat and I think that has the settings and nightmode stuff, im not sure though.

**Comment by SwiGs1** [comment]
I agree it is not easy on the eyes, bright yellow isn't very nice at least on a white background. perhaps maybe a bright or dark red? the NCR flag does have red in it? and the Legion doesn't have a radio system. So there's no worry there.

**Comment by imw-Oculus** [comment]
Red was my second gut reaction, but I was under the impression that it was already being used by some Vault channel or the other. If that's not the case, yes - red would be preferable.

**Comment by Evoturd** [comment]
Closing this IN THE FUUUUTTTUURREE! Because all factions other than BoS do not have access to radio headsets anymore. They use handhelds.
