### ISSUE TITLE
give decanus extra mags

### ISSUE THREAD

**Issue by CaptainSlumbo** [CrashpointF13/CrashpointF13#93]
The normal decanus loadout get's a rifle with only one extra magazine, I think they should get more OR get a different gun as 5.56 is hard to get as legion

**Comment by imw-Oculus** [comment]
Generally speaking, Legion is meant to be the more melee focused faction - reflected by their armor, etc - with the NCR taking the opposing role of gun-focused faction. I think one mag is appropriate, but I'll take a peek at how it plays game-to-game.
