### ISSUE TITLE
Tweak/Feature: Communal Funds for Faction Leaders

### ISSUE THREAD

**Issue by imw-Oculus** [CrashpointF13/CrashpointF13#99]
In the interest of encouraging trade and the like - I would think that one combination safe per faction (which the faction leader would get the combination to, in a memory-note on join), containing a modest-moderate amount of the appropriate currency would be advantageous.
Very low priority.

**Comment by ProbablyCarl** [comment]
Working on such in the background. Won't be priority for a bit.
